### ISSUE TITLE
shows error in communication try again , How to add test_agent_credentials ? Cannot complete fulfillment !

### ISSUE THREAD

**Issue by abhijithknamboothiri** [abhi007tyagi/DialogflowChat#11]
i followed the Medium documentation and github ! But i am unable to complete fulfillment from dialogflow ! can you help me with the issue !
is there any way to integrate dialogflow to our own application ?

**Comment by abhi007tyagi** [comment]
please be more specific?

**Comment by abhijithknamboothiri** [comment]
Can I contact you in person !
Anyways I will describe my issue in detail .
I followed your instructions , and finally added the json file to the
project through resources by remaining and placing it to the resource
folder.
But when I add json i.e test_agent_credentials ,  from there the app is
getting crashed.
But when I specify (auto suggestion / I think it is the config variable)
version_config It runs but show try again communication error is responded.

**Comment by abhi007tyagi** [comment]
first just clone the project and import your json file and run.

**Comment by abhi007tyagi** [comment]
See updated code. I have tested it on Android API version 23 and 29

**Comment by abhijithknamboothiri** [comment]
i tried the updated code .But the same issue.
When i use  this >InputStream stream = getResources().openRawResource(R.raw.
test_agent_credentials);
the app crashes.(Keeps on crashing)
Instead of this i use InputStream stream =
getResources().openRawResource(R.raw.*version_config*);
it runs fine.
the R.raw.version_config is the suggested code there.
I think the issue maybe
1.Fulfillment issue : i am unable to complete fulfillment from
dialogflow.It shows a payment prompt while going to Google cloud console
2.Client Access token is not saved in build.gradle. I have error doing that
, when i do it like you error occours.
3."There was some communication issue. Please Try again!"
because there is some error in establishing the connection with dialogflow.
4. If it isnt free to integrate a agent to android app from dialogflow ,
then is there any free api i can use
5. Can i use the webhook service ?
Can you help me please ?
Would you mind accepting my LinkedIn Connection
Abhijith.K.Namboothiry.

**Comment by abhi007tyagi** [comment]
1. Should not come. Check your Dialogflow settings in the console for payment related issues.
2. This is a simple way of hiding access keys or token in this case in Android. I would suggest removing the Client token code as it is obsolete now.
3. Your session is not created
4. It is free for basic tier up to certain number of transactions and depends on the Dialogflow tier you opted for. Check pricing info for Dialogflow
5. Yes you can
