### ISSUE TITLE
does not display the responses that comes from webhook

### ISSUE THREAD

**Issue by Nazar-Pa** [abhi007tyagi/DialogflowChat#14]
Hi first thank you for this helpful product. I am having problem when getting responses through webhook. I created a web service to get responses from external api`s, but the android application does not display the responses coming from webhook, the response field returns blank, However, all responses coming apart from webhook works flawlessly. I attach the photos here. What could be the issue? Can you please help to fix this problem?
![image](https://user-images.githubusercontent.com/55276028/87232878-c6868d80-c3c2-11ea-86ff-a7395ed9392b.png)
![108059740_905661536614269_4505446889237703314_n](https://user-images.githubusercontent.com/55276028/87232930-3ac13100-c3c3-11ea-8074-50b1c684517e.png)

**Comment by abhi007tyagi** [comment]
@Nazar-Pa answer the following 
1. do you see any server hit/call coming from your Android app to Webhook?
2. if it is coming, debug your Android app and check where it is failing and share logcat.
3. if not, are you creating a release signed build for your Android app?
4. if yes, then you may need to add some proguard rules in your app.
5. if not, then do some debugging of your Android code to see where the call is failing and share logcat.
6. Also check if you have created a signing JSON and included it in your app. see my article for details.

Proguard rules for app
`-keep public class com.google.a** {
  public protected *;
}`

If you just want to add a chatbot to your app, I have created an Android library which you can easily import.
Check the details here https://levelup.gitconnected.com/android-dialogflow-chatbot-library-6b7b3822e7bc

**Comment by Nazar-Pa** [comment]
Thank you for your reply.
1. I don't see any server hit/call coming to webhook
2. 
![image](https://user-images.githubusercontent.com/55276028/87233920-29305700-c3cc-11ea-9246-ed49b214b3fb.png)
3. actually I didn't understand, I didn't do any additional things on the app (just downloaded and built)
6. if you mean for credentials, yes I did and the app actually displays the response coming from the intent that webhook NOT enabled for the response, it only displays blank for the response that coming from the intent that webhook is enabled, I hope you got what I mean.

**Comment by Nazar-Pa** [comment]
Also there is such kind of warning.
![image](https://user-images.githubusercontent.com/55276028/87236199-42de9800-c3e6-11ea-9ad9-90adf754fc40.png)

**Comment by Nazar-Pa** [comment]
hey I fixed the issue already. It was my fault, did not set the response structure properly inside my web service code. Thanks anyway:)
