### ISSUE TITLE
Where does the "test_agent_credentials" come from?

### ISSUE THREAD

**Issue by fevziomurtekin** [abhi007tyagi/DialogflowChat#2]
I have created a test agent as you mentioned in your article. I applied everything in order. But I didn't understand where test agent credentials came from. Could you help?

**initV2Chatbot**

`  InputStream stream = getResources().openRawResource(R.raw.test_agent_credentials); `

**Comment by abhi007tyagi** [comment]
I have mentioned this in my [medium post](https://medium.com/@abhi007tyagi/android-chatbot-with-dialogflow-8c0dcc8d8018)  It comes from the Google service account using the IAM console.

**Comment by Shajeel-Afzal** [comment]
@abhi007tyagi, what is the format of test_agent_credentials? Is it .xml file or .json file? Also, credentials created in the Google Service Account using the IAM console are private. Is it safe to publish the app after including the file in the Android Project?

**Comment by abhi007tyagi** [comment]
It is json. You should not post it openly. I used this way for the demo and have not posted as well. Stor it in a server and fetch it from there in the app and then use it to access Dialogflow.
