### ISSUE TITLE
Manifest + USER and BOT

### ISSUE THREAD

**Issue by janjay2018** [abhi007tyagi/DialogflowChat#3]
Hi,

Thank you for posting your code on Github, 
I am having some trouble with user permissions, is it possible to see how your android manifest looks like? 

Also, in your main activity, you have values assigned to USER and BOT,
```java
private static final int USER = 10001;
private static final int BOT = 10002;
```
I was wondering if you could let me know where these values come from, as it seems to not be working on my computer. I was wondering whether it was the R.id for the user and bot message? 

Thank you, 
Kind regards

**Comment by abhi007tyagi** [comment]
The manifest file is already there.
And USER and BOT are just hardcoded constants just differentiate if the msg is coming from user or bot. That is a pretty straightforward thing!

**Comment by janjay2018** [comment]
Ahh yes my apologies, I see that you assigned the values in the send method and callback methods. 
Thank you for your help
