### ISSUE TITLE
Not able to find Client Access Token in the DialogFlow

### ISSUE THREAD

**Issue by Shajeel-Afzal** [abhi007tyagi/DialogflowChat#4]
Hi, 

I have followed your Medium Post and trying to configure DialofFlowChat Sample in Android Studio. For that, I need CLIENT_ACCESS_TOKEN from the DialogFlow. But for one of my project is not showing. See the screenshot attached. Note that it is showing for other agents. What is the reason for this?

<img width="530" alt="Screenshot 2019-03-10 at 2 22 32 PM" src="https://user-images.githubusercontent.com/3718283/54083052-8f244e80-4340-11e9-8900-3ab4348e47c4.png">

**Comment by abhi007tyagi** [comment]
The API.ai library is old and will be soon deprecated. Probably, the client token is being removed from new agents. Try to go to Java V2 client
