### ISSUE TITLE
Client_Access_Token

### ISSUE THREAD

**Issue by karansharma28** [abhi007tyagi/DialogflowChat#6]
Hey Abhi,
I made an chatbot last year through dialogflow API V1, and the android implementation works,
now i am trying to make V2 chatbot and hence looked at your code, i went ahead and downloaded the file but the app doesn't build inthe initial stage only, the file doesnt open. the error comes Client_Access_Token not found.

when i click on open file it takes me this file. 
please help what needs to be done in this regard.
![Screenshot (1)](https://user-images.githubusercontent.com/51983627/59738772-017dc680-9280-11e9-98a1-b913aa708861.png)

**Comment by abhi007tyagi** [comment]
@karansharma28 please see the Readme. I have shared the Medium post on how to move from V1 to V2. Client Access Token is only used in V1. For V2 you will need Google Account Credentials in JSON which I have explained in my medium post.

**Comment by karansharma28** [comment]
yeah i have the json key with me the only issue is that i dont know where to put that key in order for your source code to run.
like i said the gradle is not even building.
and your code does not have that gradle.properties file.

**Comment by abhi007tyagi** [comment]
put the json in raw folder. Just rename it as per the code. You will see the error. Gradle properties are only required for hidding client token

**Comment by abhijithknamboothiri** [comment]
> put the json in raw folder. Just rename it as per the code. You will see the error. Gradle properties are only required for hidding client token

but it then shows error ? Application closes unfortunately ?
